# The default value of `--target` used when building this crate
# in cases where it's not specified on the command line.
default-target = "wasm32-unknown-unknown"

# This will prepend a given JavaScript file to the resulting `.js` artifact.
# You can put any initialization code here which you'd like to have executed
# when your `.js` file first loads.
#
# This accepts either a string (as shown here), or an array of strings,
# in which case it will prepend all of the specified files in their
# order of appearance.
prepend-js = [
	"js_lib/three.min.js",
	"js_lib/gltf.js",
	"js_lib/simplex_noise.js",
	"js_lib/pass.js",
	"js_lib/shader_pass.js",
	"js_lib/copy_shader.js",
	"js_lib/effect_composer.js",
	"js_lib/ssao_shader.js",
	"js_lib/ssao_pass.js",
	"src/renderer.js"
]

[cargo-web]
# Asserts the minimum required version of `cargo-web` necessary
# to compile this crate; supported since 0.6.0.
minimum-version = "0.6.0"
