level = "basic"

appearance_record = [
    "StoneOutcroppingFloorRight",
    "StoneOutcroppingFloorLeft",
    "StoneOutcroppingFloorCorner",
    "StoneOutcroppingFloorBottom",
    "Skeleton",
    "Lantern",
    "StoneWall",
    "Hammer",
]
