level = "basic"

appearance_record.names = [
    "StoneOutcroppingFloorRight",
    "StoneOutcroppingFloorLeft",
    "StoneOutcroppingFloorCorner",
    "StoneOutcroppingFloorBottom",
    "Skeleton",
    "Player",
    "Lantern",
    "StoneWall",
    "StoneDoor",
    "Hammer",
]
